geekshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UsersCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UsersUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'
urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>', authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import main, contacts


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='main'),
    path('', include('social_django.urls', namespace='social')),
    path('contacts/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from .views import products, product

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='main'),
    path('category/<int:pk>/', products, name='style_category'),
    path('product/<int:pk>/', product, name='detail'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
]

geekshop/geekshop/views.py
from django.shortcuts import render
from mainapp.models import Product
# from basketapp.models import Basket


def main(request):
    title = 'Магазин'

    products = Product.objects.all()[:4]

    context = {
        'title': title,
        'products': products,
    }

    return render(request, 'geekshop/index.html', context)


def contacts(request):
    title = 'Контакты'

    context = {
        'title': title,
    }

    return render(request, 'geekshop/contact.html', context)

geekshop/geekshop/templates/geekshop/includes/details.html
{% load static %}
<div class="details">
			<div class="links clearfix">
				<ul class="links-menu">
						<li><a href="{% url 'products:style_category' 0 %}" class="
								{% if request.resolver_match.kwargs.pk == 0 %}
									active
								{% endif %}">
								все
							</a>
						</li>
					{% for link in links_menu %}
						<li><a href="{% url 'products:style_category' link.pk %}" class="
								{% if request.resolver_match.kwargs.pk|add:0 == link.pk %}
									active
								{% endif %}">
								{{ link.name }}
							</a>
						</li>
					{% endfor %}
				</ul>
			</div>

			{% if hot_product %}
			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="/media/{{ hot_product.image }}">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="{% static 'geekshop/img/controll.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'geekshop/img/controll1.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'geekshop/img/controll2.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">{{ hot_product.name }}</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price">{{ hot_product.price }}<span>руб.</span></p>
					<a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						{{ hot_product.description }}
					</div>
				</div>
			</div>
			{% endif %}

			<div class="products_list">
				<div class="title clearfix">
					{% if style_category %}
					<h2>
						Категория: "{{ style_category.name|title }}"
					</h2>
					{% endif %}
				</div>
				<div class="paginator">
					{% if products.has_previous %}
						<a href="{% url 'products:page' style_category.pk products.previous_page_number %}">
							<
						</a>
					{% endif %}
					{% if products.has_previous or products.has_next  %}
						<span class="current">страница {{ products.number }} из	{{ products.paginator.num_pages }}
						</span>
					{% endif %}
					{% if products.has_next %}
						<a href="{% url 'products:page' style_category.pk products.next_page_number %}">
							>
						</a>
					{% endif %}
				</div>



				<br>
				<div class="category-products clearfix related-products">
					{% for product in products %}
						<div class="block">
							<a href="{% url 'products:detail' product.pk %}">
								<img src="/media/{{ product.image }}" alt="product">
								<div class="text">
									<img src="{% static 'img/icon-hover.png' %}" alt="hover">
									<h4>{{ product.name }}</h4>
									<p>{{ product.description }}</p>
								</div>
							</a>
						</div>
					{% endfor %}
				</div>
			</div>

			{% if same_products %}
			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products ">
					{% for same_product in same_products %}
					<div class="block">
						<a href="{% url 'products:detail' same_product.pk %}"><img src="/media/{{ same_product.image }}" alt="">
							<div class="text">
								<img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
								<h4>{{ same_product.name }}</h4>
								<p>{{ same_product.description }}</p>
							</div>
						</a>
					</div>
					{% endfor %}
				</div>
			</div>
			{% endif %}
		</div>

geekshop/geekshop/templates/geekshop/includes/featured.html
{% load static %}
<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				{% for product in products %}
					<div class="block">
						<a href="#"><img src="/media/{{ product.image }}" alt="">
							<div class="text">
								<img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
								<h4>{{ product.short_desc }}</h4>
								<p>{{ product.description }}</p>
							</div>
						</a>
					</div>
				{% endfor %}
			</div>
		</div>

geekshop/geekshop/templates/geekshop/includes/hero-white.html
<div class="hero-white">
	<div class="header clearfix">
		{% include 'geekshop/includes/logo.html' %}
		{% include 'geekshop/includes/menu.html' %}
		{% include 'geekshop/includes/search+basket.html' %}
	</div>
</div>

geekshop/geekshop/templates/geekshop/includes/hero.html
<div class="hero">
			<div class="header clearfix">
				{% include 'geekshop/includes/logo.html' %}
				{% include 'geekshop/includes/menu.html' %}
				{% include 'geekshop/includes/search+basket.html' %}
			</div>
			<h1>наши контакты</h1>
		</div>

geekshop/geekshop/templates/geekshop/includes/location.html
<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>

geekshop/geekshop/templates/geekshop/includes/logo.html
<a href="{% url 'main' %}" class="logo"></a>

geekshop/geekshop/templates/geekshop/includes/menu.html
{% load static %}
<ul class="menu">
    {{ context.title }}
    <li><a href="{% url 'main' %}"
           class="{% if title == 'Магазин' %}
                active
                {% endif %}">домой</a></li>
    <li><a href="{% url 'products:main' %}"
           class="{% if title == 'Каталог' %}
                active
                {% endif %}">продукты</a></li>
    <li><a href="{% url 'contacts' %}"
           class="{% if title == 'Контакты' %}
                active
                {% endif %}">контакты</a></li>

    {% if user.is_authenticated %}
        <li class="dropdown-toggle" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                <a>{{ user.first_name|default:'Пользователь' }}</a>
            </li>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li>
                    <a class="dropdown-item" href="{% url 'auth:edit' %}">
                        Профиль</a>
                </li>
                {% if user.is_superuser %}
                    <li><a class="dropdown-item" href="{% url 'admin_staff:users' %}">Админка</a>
                    </li>
                {% endif %}
                {% if basket %}
                    <li><a class="dropdown-item" href="{% url 'basket:view' %}">Корзина</a>
                    </li>
                {% endif %}
                    <li><a class="dropdown-item" href="{% url 'orders:main' %}">Заказы</a>
                    </li>
                <li>
                    {% if user.is_authenticated %}
                        <a href="{% url 'auth:logout' %}">выйти</a>
                    {% endif %}
                </li>
            </ul>

            {% if basket %}
                <span>
                    {{ basket.0.total_cost|floatformat:0 }} руб.
                    ({{ basket.0.total_quantity }} шт.)
                </span>
            {% endif %}

    {% endif %}

    {% if not user.is_authenticated %}
        <a href="{% url 'auth:login' %}">войти</a>
    {% endif %}


</ul>

geekshop/geekshop/templates/geekshop/includes/search+basket.html
<a href="#" class="search"></a>
<a href="#" class="basket"></a>

geekshop/geekshop/templates/geekshop/includes/slider.html
{% load static %}
<div class="slider">
			<div class="header clearfix">
				{% include 'geekshop/includes/logo.html' %}
				{% include 'geekshop/includes/menu.html' %}
				<a href="#" class="search"></a>
			</div>
			<div class="text-slider">
				<h3 class="green">тенденции {% now 'Y' %} года</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
			</div>
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>